### ISSUE TITLE
Helm Charts template testing is failing with `TypeError: attrib() got an unexpected keyword argument 'convert'`

### ISSUE THREAD

**Issue by jmlrt** [elastic/helm-charts#308]
Running `make test` for any Helm Charts for template testing is giving us this [error](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/186/CHART=elasticsearch,label=docker&&virtual/console):

```

17:55:32 pytest -sv --color=yes
17:55:32 Traceback (most recent call last):
17:55:32   File "/usr/local/bin/pytest", line 10, in <module>
17:55:32     sys.exit(main())
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 61, in main
17:55:32     config = _prepareconfig(args, plugins)
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
17:55:32     config = get_config()
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 156, in get_config
17:55:32     pluginmanager.import_plugin(spec)
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 530, in import_plugin
17:55:32     __import__(importspec)
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/tmpdir.py", line 25, in <module>
17:55:32     class TempPathFactory(object):
17:55:32   File "/usr/local/lib/python3.7/site-packages/_pytest/tmpdir.py", line 35, in TempPathFactory
17:55:32     lambda p: Path(os.path.abspath(six.text_type(p)))
17:55:32 TypeError: attrib() got an unexpected keyword argument 'convert'
17:55:32 make: *** [../helpers/common.mk:17: pytest] Error 1
```

This is a blocker for #307.

**Comment by jmlrt** [comment]
This seem related to #297 since `make test` is OK with old Docker images build from `python:2.7-onbuild` and `python:3.6-onbuild` but not `python:3.7`.

However build with `python:3.7` was OK until [elastic+helm-charts+pull-request+template-testing/183](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/183/) and started to fail 30 minutes later ([elastic+helm-charts+pull-request+template-testing/184](https://devops-ci.elastic.co/job/elastic+helm-charts+pull-request+template-testing/184/)) while nothing changed between the 2 builds.

Note that this is also happening on `master` branch [build](https://devops-ci.elastic.co/job/elastic+helm-charts+master+template-testing/CHART=elasticsearch,label=docker&&virtual/200).
